"""
CORD Cron - Document & Report Generator (Word .docx, Markdown, HTML)
Generates structured Microsoft Word (.docx) documents and markdown briefings for automated jobs.
"""

from __future__ import annotations
import os
import time
from pathlib import Path
from typing import Dict, List, Any, Optional

try:
    import docx
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False


class ReportGenerator:
    """Generates professional Word (.docx) and Markdown briefings."""

    @staticmethod
    def generate_docx(
        title: str,
        sections: List[Dict[str, Any]],
        output_path: str,
        subtitle: Optional[str] = None,
        author: str = "CORD Autonomous Agent",
    ) -> str:
        """
        Creates a formatted Microsoft Word (.docx) file.
        sections format:
        [
            {"heading": "1. Executive Summary", "content": "Summary text..."},
            {"heading": "2. Highlights", "bullets": ["Point A", "Point B"]},
            {"heading": "3. Data Table", "table": {"headers": ["A", "B"], "rows": [["1", "2"]]}},
        ]
        """
        out_p = Path(output_path).expanduser().resolve()
        out_p.parent.mkdir(parents=True, exist_ok=True)

        if not DOCX_AVAILABLE:
            # Fallback to markdown if python-docx isn't available
            md_path = str(out_p.with_suffix(".md"))
            ReportGenerator.generate_markdown(title, sections, md_path, subtitle=subtitle)
            return md_path

        doc = docx.Document()

        # Title
        t_p = doc.add_paragraph()
        t_run = t_p.add_run(title)
        t_run.font.size = Pt(24)
        t_run.font.bold = True
        t_run.font.color.rgb = RGBColor(14, 116, 144)  # Deep cyan
        t_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Subtitle
        if subtitle:
            sub_p = doc.add_paragraph()
            sub_run = sub_p.add_run(subtitle)
            sub_run.font.size = Pt(13)
            sub_run.font.italic = True
            sub_run.font.color.rgb = RGBColor(100, 116, 139)
            sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Metadata bar
        meta_p = doc.add_paragraph()
        meta_run = meta_p.add_run(f"Generated by {author} │ {time.strftime('%Y-%m-%d %H:%M:%S')}")
        meta_run.font.size = Pt(9)
        meta_run.font.color.rgb = RGBColor(148, 163, 184)
        meta_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()  # Blank spacing

        # Sections
        for sec in sections:
            heading = sec.get("heading")
            if heading:
                h_p = doc.add_heading(heading, level=sec.get("level", 1))
                h_p.paragraph_format.space_before = Pt(12)
                h_p.paragraph_format.space_after = Pt(4)

            content = sec.get("content")
            if content:
                for line in str(content).split("\n"):
                    if line.strip():
                        p = doc.add_paragraph(line.strip())
                        p.paragraph_format.line_spacing = 1.15
                        p.paragraph_format.space_after = Pt(4)

            bullets = sec.get("bullets", [])
            for b in bullets:
                p = doc.add_paragraph(str(b), style="List Bullet")
                p.paragraph_format.space_after = Pt(2)

            # Tables
            table_data = sec.get("table")
            if table_data and isinstance(table_data, dict):
                headers = table_data.get("headers", [])
                rows = table_data.get("rows", [])
                if headers:
                    t = doc.add_table(rows=len(rows) + 1, cols=len(headers))
                    t.style = "Table Grid"
                    # Header row
                    hdr_cells = t.rows[0].cells
                    for i, h in enumerate(headers):
                        hdr_cells[i].text = str(h)
                        for r in hdr_cells[i].paragraphs[0].runs:
                            r.font.bold = True
                    # Data rows
                    for r_idx, row in enumerate(rows):
                        row_cells = t.rows[r_idx + 1].cells
                        for c_idx, val in enumerate(row):
                            if c_idx < len(row_cells):
                                row_cells[c_idx].text = str(val)
                    doc.add_paragraph()  # Spacing after table

        doc.save(str(out_p))
        return str(out_p)

    @staticmethod
    def generate_markdown(
        title: str,
        sections: List[Dict[str, Any]],
        output_path: str,
        subtitle: Optional[str] = None,
    ) -> str:
        """Creates a formatted Markdown report."""
        out_p = Path(output_path).expanduser().resolve()
        out_p.parent.mkdir(parents=True, exist_ok=True)

        lines = [f"# {title}\n"]
        if subtitle:
            lines.append(f"> *{subtitle}*\n")
        lines.append(f"*Generated by CORD Autonomous Agent on {time.strftime('%Y-%m-%d %H:%M:%S')}*\n\n---\n")

        for sec in sections:
            if sec.get("heading"):
                level = sec.get("level", 2)
                prefix = "#" * max(level, 2)
                lines.append(f"\n{prefix} {sec['heading']}\n")
            if sec.get("content"):
                lines.append(f"{sec['content']}\n")
            if sec.get("bullets"):
                for b in sec["bullets"]:
                    lines.append(f"- {b}")
                lines.append("")
            if sec.get("table"):
                headers = sec["table"].get("headers", [])
                rows = sec["table"].get("rows", [])
                if headers:
                    lines.append("| " + " | ".join(headers) + " |")
                    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
                    for row in rows:
                        lines.append("| " + " | ".join(str(c) for c in row) + " |")
                    lines.append("")

        out_p.write_text("\n".join(lines), encoding="utf-8")
        return str(out_p)


report_generator = ReportGenerator()
